{
 "title": "Gitlab",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "gitlab_database_connection_pool",
    "label": "DB pool",
    "query": {
     "query": "label_values(gitlab_database_connection_pool_size,app)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Repositories",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(gitaly_total_repositories_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Runners",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(gitlab_runner_concurrent)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Database connections pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "$gitlab_database_connection_pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "repeat": "gitlab_database_connection_pool",
   "targets": [
    {
     "expr": "max(gitlab_database_connection_pool_size{app=\"$gitlab_database_connection_pool\"})",
     "legendFormat": "pool size"
    },
    {
     "expr": "avg(avg_over_time(gitlab_database_connection_pool_connections{app=\"$gitlab_database_connection_pool\"}[$__interval]))",
     "legendFormat": "connections"
    },
    {
     "expr": "avg(avg_over_time(gitlab_database_connection_pool_busy{app=\"$gitlab_database_connection_pool\"}[$__interval]))",
     "legendFormat": "busy"
    },
    {
     "expr": "avg(avg_over_time(gitlab_database_connection_pool_dead{app=\"$gitlab_database_connection_pool\"}[$__interval]))",
     "legendFormat": "dead"
    },
    {
     "expr": "avg(avg_over_time(gitlab_database_connection_pool_idle{app=\"$gitlab_database_connection_pool\"}[$__interval]))",
     "legendFormat": "idle"
    },
    {
     "expr": "avg(avg_over_time(gitlab_database_connection_pool_waiting{app=\"$gitlab_database_connection_pool\"}[$__interval]))",
     "legendFormat": "waiting"
    }
   ]
  },
  { "title": "Runner jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Runner jobs results",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(delta(gitlab_runner_failed_jobs_total[$__rate_interval])) by (failure_reason)",
     "legendFormat": "{{failure_reason}}"
    },
    {
     "expr": "sum(delta(gitlab_runner_jobs_total [$__rate_interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Runner job duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(gitlab_runner_job_duration_seconds_sum[$__rate_interval])/rate(gitlab_runner_job_duration_seconds_count[$__rate_interval])",
     "legendFormat": "{{app}} : {{runner}} : {{job}}"
    }
   ]
  },
  {
   "title": "Runner job durations",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum by (le) (\n  increase(gitlab_runner_job_duration_seconds_bucket{}[$__rate_interval])\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Runner job queue durations",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "sum by (le) (\n  increase(gitlab_runner_job_queue_duration_seconds_bucket{}[$__rate_interval])\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Runner errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum(increase(gitlab_runner_errors_total[$__rate_interval])) by (level)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "User authenticated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "increase(gitlab_auth_user_authenticated_total[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "User unauthenticated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "sum(delta(gitlab_auth_user_unauthenticated_total{}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Http requests total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum(delta(http_requests_total[$__rate_interval])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Request duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "sum by (le) (\n  increase(http_request_duration_seconds_bucket{}[$__rate_interval])\n)\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}